In [1]:
#importing my pandas & datetime library

import pandas as pd
import datetime

In [2]:
#coverting my data into pandas dataframe
df = pd.read_csv(r'C:\Users\Prince Gee\Downloads\chicago2.csv')

In [11]:
df

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,53000,4809324,HM300447,04/19/2006 04:45:02 PM,090XX S NORMAL AVE,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,RESIDENCE,False,...,21.0,71.0,18,1174545.0,1845186.0,2006,02/10/2018 03:50:01 PM,41.730582,-87.636172,"(41.730582057, -87.636172403)"
1,53001,2599849,HJ197748,02/21/2003 06:30:00 PM,039XX N AVONDALE AVE,0820,THEFT,$500 AND UNDER,STREET,False,...,38.0,16.0,06,1147850.0,1926182.0,2003,02/28/2018 03:56:25 PM,41.953398,-87.731888,"(41.953397577, -87.73188822)"
2,53002,7495181,HR183541,02/22/2009 07:42:00 PM,011XX S CALIFORNIA AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,OTHER,False,...,28.0,29.0,08B,NaN,NaN,2009,08/17/2015 03:03:40 PM,NaN,NaN,NaN
3,53003,2628412,HJ231141,03/07/2003 02:46:00 PM,025XX W ADDISON ST,0890,THEFT,FROM BUILDING,"SCHOOL, PUBLIC, BUILDING",False,...,47.0,5.0,06,1158854.0,1923830.0,2003,02/28/2018 03:56:25 PM,41.946725,-87.691501,"(41.946724511, -87.691501175)"
4,53004,8389615,HT622350,12/06/2011 12:00:00 AM,072XX S MAY ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,...,17.0,68.0,26,1169905.0,1856761.0,2011,02/04/2016 06:33:39 AM,41.762447,-87.652835,"(41.762447305, -87.652834901)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,53995,9619330,HX269158,05/19/2014 06:00:00 PM,088XX S WABASH AVE,5002,OTHER OFFENSE,OTHER VEHICLE OFFENSE,STREET,False,...,6.0,44.0,26,1178260.0,1846297.0,2014,02/04/2016 06:33:39 AM,41.733547,-87.622530,"(41.733547403, -87.622529593)"
996,53996,11053559,JA390202,08/11/2017 04:00:00 PM,137XX S JEFFERY AVE,0610,BURGLARY,FORCIBLE ENTRY,FACTORY/MANUFACTURING BUILDING,False,...,10.0,55.0,05,1191658.0,1814171.0,2017,02/10/2018 03:50:01 PM,41.645076,-87.574483,"(41.645075822, -87.574483491)"
997,53997,12023154,JD201316,03/21/2020 09:00:00 AM,058XX N WHIPPLE ST,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,RESIDENCE,False,...,40.0,2.0,11,1154971.0,1938707.0,2020,04/08/2020 03:49:33 PM,41.987627,-87.705373,"(41.987626778, -87.705373183)"
998,53998,1604980,G367198,06/23/2001 05:00:00 PM,070XX S OGLESBY AV,0820,THEFT,$500 AND UNDER,STREET,False,...,NaN,NaN,06,1192939.0,1858982.0,2001,08/17/2015 03:03:40 PM,41.768011,-87.568341,"(41.768010848, -87.568340708)"
999,53999,2660948,HJ275409,04/01/2003 10:00:00 AM,030XX S THROOP ST,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE-GARAGE,False,...,11.0,60.0,05,1170351.0,1884713.0,2003,02/10/2018 03:50:01 PM,41.839141,-87.650386,"(41.839140939, -87.650386262)"

In [63]:
# Identify redundant columns
redundant_cols = ["Case Number"]  
# Drop redundant columns
df_cleaned = df.drop(columns=redundant_cols)

In [64]:
df_cleaned

,Unnamed: 0,ID,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,53000,4809324,04/19/2006 04:45:02 PM,090XX S NORMAL AVE,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,RESIDENCE,False,False,...,21.0,71.0,18,1174545.0,1845186.0,2006,02/10/2018 03:50:01 PM,41.730582,-87.636172,"(41.730582057, -87.636172403)"
1,53001,2599849,02/21/2003 06:30:00 PM,039XX N AVONDALE AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,38.0,16.0,06,1147850.0,1926182.0,2003,02/28/2018 03:56:25 PM,41.953398,-87.731888,"(41.953397577, -87.73188822)"
2,53002,7495181,02/22/2009 07:42:00 PM,011XX S CALIFORNIA AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,OTHER,False,False,...,28.0,29.0,08B,NaN,NaN,2009,08/17/2015 03:03:40 PM,NaN,NaN,NaN
3,53003,2628412,03/07/2003 02:46:00 PM,025XX W ADDISON ST,0890,THEFT,FROM BUILDING,"SCHOOL, PUBLIC, BUILDING",False,False,...,47.0,5.0,06,1158854.0,1923830.0,2003,02/28/2018 03:56:25 PM,41.946725,-87.691501,"(41.946724511, -87.691501175)"
4,53004,8389615,12/06/2011 12:00:00 AM,072XX S MAY ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,True,...,17.0,68.0,26,1169905.0,1856761.0,2011,02/04/2016 06:33:39 AM,41.762447,-87.652835,"(41.762447305, -87.652834901)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,53995,9619330,05/19/2014 06:00:00 PM,088XX S WABASH AVE,5002,OTHER OFFENSE,OTHER VEHICLE OFFENSE,STREET,False,True,...,6.0,44.0,26,1178260.0,1846297.0,2014,02/04/2016 06:33:39 AM,41.733547,-87.622530,"(41.733547403, -87.622529593)"
996,53996,11053559,08/11/2017 04:00:00 PM,137XX S JEFFERY AVE,0610,BURGLARY,FORCIBLE ENTRY,FACTORY/MANUFACTURING BUILDING,False,False,...,10.0,55.0,05,1191658.0,1814171.0,2017,02/10/2018 03:50:01 PM,41.645076,-87.574483,"(41.645075822, -87.574483491)"
997,53997,12023154,03/21/2020 09:00:00 AM,058XX N WHIPPLE ST,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,RESIDENCE,False,False,...,40.0,2.0,11,1154971.0,1938707.0,2020,04/08/2020 03:49:33 PM,41.987627,-87.705373,"(41.987626778, -87.705373183)"
998,53998,1604980,06/23/2001 05:00:00 PM,070XX S OGLESBY AV,0820,THEFT,$500 AND UNDER,STREET,False,False,...,NaN,NaN,06,1192939.0,1858982.0,2001,08/17/2015 03:03:40 PM,41.768011,-87.568341,"(41.768010848, -87.568340708)"
999,53999,2660948,04/01/2003 10:00:00 AM,030XX S THROOP ST,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE-GARAGE,False,False,...,11.0,60.0,05,1170351.0,1884713.0,2003,02/10/2018 03:50:01 PM,41.839141,-87.650386,"(41.839140939, -87.650386262)"

In [123]:
# Extract month, day,"Date" column
df_cleaned["Month"] = pd.to_datetime(df_cleaned["Date"], format="%m/%d/%Y %I:%M %p").dt.month_name()  #Extracts month
df_cleaned["Day"] = pd.to_datetime(df_cleaned["Date"], format="%m/%d/%Y %I:%M %p").dt.day_name()   #extracts day

In [124]:
# creating a column for seasons

def create_seasons_column(date_column):
    """
    Creates a new column representing seasons based on the months in a datetime column.

    Parameters:
    - date_column: Pandas Series, representing a datetime feature

    Returns:
    - Pandas Series containing the corresponding season names
    """
    # coverting  input to  datetime format
    date_column = pd.to_datetime(date_column, format='%m/%d/%Y %I:%M:%S %p', errors='coerce')

    # Define a mapping of the month to season
    month_to_season = {
        1: 'Winter', 2: 'Winter', 3: 'Spring',
        4: 'Spring', 5: 'Spring', 6: 'Summer',
        7: 'Summer', 8: 'Summer', 9: 'Fall',
        10: 'Fall', 11: 'Fall', 12: 'Winter'
    }

    # Extract the month and map to season
    seasons_column = date_column.dt.month.map(month_to_season)

    return seasons_column

In [118]:

df_cleaned['Season'] = create_seasons_column(df_cleaned['Date'])

In [120]:
df_cleaned.loc[:, 'Season'].head()

0    Spring
1    Winter
2    Winter
3    Spring
4    Winter
Name: Season, dtype: object

In [125]:
df_cleaned.head()

,Unnamed: 0,ID,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Month,Day,Season
0,53000,4809324,2006-04-19,090XX S NORMAL AVE,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,RESIDENCE,False,False,...,1174545.0,1845186.0,2006,02/10/2018 03:50:01 PM,41.730582,-87.636172,"(41.730582057, -87.636172403)",April,Wednesday,Spring
1,53001,2599849,2003-02-21,039XX N AVONDALE AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,1147850.0,1926182.0,2003,02/28/2018 03:56:25 PM,41.953398,-87.731888,"(41.953397577, -87.73188822)",February,Friday,Winter
2,53002,7495181,2009-02-22,011XX S CALIFORNIA AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,OTHER,False,False,...,NaN,NaN,2009,08/17/2015 03:03:40 PM,NaN,NaN,NaN,February,Sunday,Winter
3,53003,2628412,2003-03-07,025XX W ADDISON ST,0890,THEFT,FROM BUILDING,"SCHOOL, PUBLIC, BUILDING",False,False,...,1158854.0,1923830.0,2003,02/28/2018 03:56:25 PM,41.946725,-87.691501,"(41.946724511, -87.691501175)",March,Friday,Spring
4,53004,8389615,2011-12-06,072XX S MAY ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,True,...,1169905.0,1856761.0,2011,02/04/2016 06:33:39 AM,41.762447,-87.652835,"(41.762447305, -87.652834901)",December,Tuesday,Winter

In [126]:
df_cleaned.dtypes

Unnamed: 0                       int64
ID                               int64
Date                    datetime64[ns]
Block                           object
IUCR                            object
Primary Type                    object
Description                     object
Location Description            object
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
FBI Code                        object
X Coordinate                   float64
Y Coordinate                   float64
Year                             int32
Updated On                      object
Latitude                       float64
Longitude                      float64
Location                        object
Month                           object
Day                             object
Season                          object
dtype: object

In [127]:
# Group by Months, Days, Seasons and count crimes
crime_counts_month = df_cleaned.groupby("Month")["Primary Type"].count()
crime_counts_day = df_cleaned.groupby("Day")["Primary Type"].count()
crime_counts_season = df_cleaned.groupby("Season")["Primary Type"].count()

# Find months, days, seasons with highest and lowest crime
highest_crime_month = crime_counts_month.idxmax()
lowest_crime_month = crime_counts_month.idxmin()
highest_crime_day = crime_counts_day.idxmax()
lowest_crime_day = crime_counts_day.idxmin()
highest_crime_season = crime_counts_season.idxmax()
lowest_crime_season = crime_counts_season.idxmin()

# Find highest and lowest crimes by frequency
highest_crimes = df_cleaned["Primary Type"].value_counts().head(5).index.tolist()
lowest_crimes = df_cleaned["Primary Type"].value_counts().tail(5).index.tolist()

# Print results
print(f"Month with highest crime: {highest_crime_month}")
print(f"Month with lowest crime: {lowest_crime_month}")
print(f"Day with highest crime: {highest_crime_day}")
print(f"Day with lowest crime: {lowest_crime_day}")
print(f"Season with highest crime: {highest_crime_season}")
print(f"Season with lowest crime: {lowest_crime_season}")
print(f"Highest occurrence crimes: {highest_crimes}")
print(f"Lowest occurrence crimes: {lowest_crimes}")

Month with highest crime: July
Month with lowest crime: February
Day with highest crime: Monday
Day with lowest crime: Thursday
Season with highest crime: Spring
Season with lowest crime: Winter
Highest occurrence crimes: ['THEFT', 'BATTERY', 'CRIMINAL DAMAGE', 'NARCOTICS', 'OTHER OFFENSE']
Lowest occurrence crimes: ['GAMBLING', 'KIDNAPPING', 'LIQUOR LAW VIOLATION', 'STALKING', 'CRIM SEXUAL ASSAULT']

In [128]:
# Group by location description and count crimes
crime_counts_location = df_cleaned.groupby("Location Description")["Primary Type"].count()

# Find location with highest crime
highest_crime_location = crime_counts_location.idxmax()

# Print result
print(f"Location with highest crime: {highest_crime_location}")

Location with highest crime: STREET

In [129]:
# Group by year and primary type, then count crimes
crime_counts_year = (
    df_cleaned.groupby(["Year", "Primary Type"])["ID"]
    .count()
    .reset_index()
    .rename(columns={"ID": "Count"})
)

# Pivot table to show crime type evolution across years
pivot_table = crime_counts_year.pivot_table(
    index="Year", columns="Primary Type", values="Count", aggfunc="sum"
)

In [130]:
pivot_table

Primary Type,ASSAULT,BATTERY,BURGLARY,CRIM SEXUAL ASSAULT,CRIMINAL DAMAGE,CRIMINAL TRESPASS,DECEPTIVE PRACTICE,GAMBLING,HOMICIDE,INTERFERENCE WITH PUBLIC OFFICER,...,NARCOTICS,OFFENSE INVOLVING CHILDREN,OTHER OFFENSE,PROSTITUTION,PUBLIC PEACE VIOLATION,ROBBERY,SEX OFFENSE,STALKING,THEFT,WEAPONS VIOLATION
Year,,,,,,,,,,,,,,,,,,,,,
2001,2.0,16.0,4.0,NaN,3.0,2.0,1.0,NaN,NaN,NaN,...,3.0,NaN,1.0,1.0,NaN,3.0,NaN,NaN,14.0,NaN
2002,4.0,13.0,3.0,NaN,9.0,1.0,2.0,1.0,NaN,NaN,...,3.0,2.0,6.0,NaN,NaN,3.0,NaN,NaN,7.0,NaN
2003,3.0,10.0,1.0,NaN,8.0,3.0,1.0,NaN,NaN,NaN,...,3.0,1.0,1.0,1.0,NaN,5.0,2.0,NaN,10.0,NaN
2004,4.0,17.0,4.0,NaN,7.0,2.0,NaN,NaN,NaN,NaN,...,5.0,1.0,7.0,2.0,NaN,3.0,NaN,NaN,16.0,1.0
2005,1.0,10.0,3.0,NaN,8.0,5.0,3.0,NaN,NaN,NaN,...,7.0,NaN,5.0,2.0,NaN,7.0,NaN,NaN,20.0,NaN
2006,1.0,10.0,4.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,...,8.0,NaN,5.0,NaN,NaN,2.0,NaN,NaN,14.0,1.0
2007,4.0,10.0,7.0,1.0,5.0,2.0,1.0,NaN,NaN,NaN,...,7.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,11.0,NaN
2008,2.0,12.0,4.0,NaN,6.0,2.0,2.0,NaN,NaN,NaN,...,8.0,2.0,4.0,NaN,NaN,1.0,NaN,NaN,7.0,NaN
2009,4.0,8.0,4.0,NaN,5.0,1.0,1.0,NaN,NaN,NaN,...,6.0,NaN,4.0,1.0,1.0,2.0,NaN,NaN,9.0,NaN
2010,1.0,7.0,4.0,NaN,7.0,4.0,4.0,1.0,NaN,NaN,...,8.0,NaN,3.0,NaN,NaN,1.0,1.0,NaN,14.0,1.0
2011,3.0,6.0,3.0,NaN,5.0,2.0,2.0,NaN,NaN,1.0,...,5.0,1.0,2.0,NaN,NaN,1.0,1.0,NaN,4.0,NaN
2012,4.0,4.0,2.0,NaN,3.0,NaN,5.0,NaN,NaN,NaN,...,6.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,18.0,NaN
2013,3.0,6.0,3.0,NaN,6.0,NaN,NaN,NaN,NaN,1.0,...,7.0,1.0,3.0,1.0,1.0,3.0,NaN,NaN,10.0,NaN
2014,4.0,9.0,4.0,NaN,5.0,NaN,5.0,NaN,NaN,NaN,...,5.0,1.0,5.0,NaN,NaN,1.0,NaN,NaN,3.0,NaN
2015,2.0,7.0,2.0,NaN,3.0,NaN,2.0,NaN,NaN,NaN,...,1.0,NaN,4.0,NaN,NaN,2.0,NaN,NaN,9.0,NaN
2016,3.0,8.0,1.0,NaN,6.0,1.0,6.0,NaN,1.0,NaN,...,2.0,1.0,4.0,NaN,NaN,1.0,NaN,NaN,10.0,NaN
2017,2.0,4.0,3.0,NaN,3.0,NaN,2.0,NaN,NaN,NaN,...,1.0,NaN,4.0,NaN,NaN,2.0,NaN,1.0,6.0,NaN
2018,1.0,5.0,3.0,NaN,1.0,1.0,NaN,NaN,1.0,1.0,...,5.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,6.0,NaN
2019,2.0,10.0,3.0,NaN,8.0,3.0,1.0,NaN,NaN,NaN,...,2.0,NaN,2.0,NaN,1.0,1.0,NaN,NaN,12.0,2.0
2020,2.0,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,1.0,...,1.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0
2021,2.0,7.0,NaN,NaN,3.0,NaN,6.0,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,1.0,2.0,NaN,NaN,2.0,NaN
2022,NaN,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0